python: can't open file '/home/ubuntu/digital-evidence-pipeline/evidence_collector.py': [Errno 2] No such file or directory
